kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: ${MINIKUBE_URL}
          name: minikube
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
          serviceAccountToken: ${MINIKUBE_TOKEN}
        - url: https://backstage--k8s-backstage-de-038239-srt0pdkp.hcp.spaincentral.azmk8s.io
          name: backstage-cluster
          authProvider: azure
          skipTLSVerify: true