# Backstage override configuration for your local development environment
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    guest: {}
    github:
      development:
        clientId: <your-client-id>
        clientSecret: <your-client-secret>
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: ${MINIKUBE_URL}
          name: minikube
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
          serviceAccountToken: ${MINIKUBE_TOKEN}
        - url: https://backstage--k8s-backstage-de-038239-srt0pdkp.hcp.spaincentral.azmk8s.io
          name: backstage-cluster
          authProvider: azure
          skipTLSVerify: true