@api_url = http://localhost:7007/api/
@access_token = hJH1SgtEaLHIMREu3W+xZqa1i/kqslzx

###

GET {{ api_url }}catalog/entities HTTP/1.1
Authorization: Bearer {{access_token}}

###

GET {{ api_url }}catalog/entities/by-query?filter=kind=component HTTP/1.1
Authorization: Bearer {{access_token}}

###

# Search for a specific entity using the entity name

GET {{ api_url }}catalog/entities/by-query?filter=metadata.name=heroes-python-web HTTP/1.1
Authorization: Bearer {{access_token}}

###

# Search for a specific entity using the entity name

GET {{ api_url }}catalog/entities/by-query?filter=metadata.name=heroes-java-api HTTP/1.1
Authorization: Bearer {{access_token}}

###

# Search for a specific entity using the entity name

GET {{ api_url }}catalog/entities/by-query?&filter=metadata.name=nodejs-backstage-template HTTP/1.1
Authorization: Bearer {{access_token}}

###

GET {{ api_url }}catalog/entities/by-query?filter=kind=user HTTP/1.1
Authorization: Bearer {{access_token}}

###

GET {{ api_url }}catalog/entities/by-query?&filter=kind%3Dtemplate HTTP/1.1
Authorization: Bearer {{access_token}}

###

# Create a repo using a software template

POST {{ api_url }}scaffolder/v2/tasks HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=utf-8

{
  "templateRef": "template:default/dotnet8-template",
  "values": {
    "name": "youtube-demo",
    "description": "This is a demo for the youtube video",
    "owner": "0GiS0",
    "repoUrl": "github.com?owner=0GiS0&repo=youtube-demo",
    "system": "system:default/tour-of-heroes"
  }
}


###

# Get the status of the task
@task_id = 84a02535-7ec3-4c99-b76a-5a7aa455779e

GET {{ api_url }}scaffolder/v2/tasks/{{task_id}} HTTP/1.1
Authorization: Bearer {{access_token}}