apiVersion: v1
kind: Service
metadata:
  labels:
    app: tour-of-heroes-sql
    'backstage.io/kubernetes-id': tour-of-heroes
  name: tour-of-heroes-sql
  namespace: tour-of-heroes
spec:
  ports:
    - name: sqlserverport
      port: 1433
      targetPort: 1433
  selector:
    app: tour-of-heroes-sql