apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pvc
  labels:
    'backstage.io/kubernetes-id': tour-of-heroes
  namespace: tour-of-heroes
spec:  
  storageClassName: managed-csi  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi