name: CI

on:
  push:
    branches:
      - microsoft-and-gh

jobs:
  build:       
    runs-on: ubuntu-latest     

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install
      working-directory: backstage      

    - name: Build project
      run: yarn run build:all
      working-directory: backstage

    - name: Run tests
      run: yarn run test:all
      working-directory: backstage